QuanLyYTe/Models/TrinhKy.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace QuanLyYTe.Models
{
    public class TrinhKy
    {
        [Key]
        public int ID_TK { get; set; }
        public int ID_PhongBan { get; set; }
        [NotMapped]
        public string? TenPhongBan { get; set; }
        public string? NoiDung { get; set; }
        public DateTime? NgayTrinhKy { get; set; }
        public string? FilePath { get; set; }
        public Nullable<int> NguoiLap { get; set; }
        [NotMapped]
        public string? MaNV_NguoiLap { get; set; }
        [NotMapped]
        public string? HoTen_NguoiLap { get; set; }
        public Nullable<int> TinhTrang_NguoiLap { get; set; }
        public DateTime? Ngay_NguoiLap { get; set; }

        public Nullable< int> TruongPho { get; set; }
        [NotMapped]
        public string? HoTen_TruongPho { get; set; }
        public Nullable<int> TinhTrang_TruongPho { get; set; }
        public DateTime? Ngay_TruongPho { get; set; }
        public string? GhiChu { get; set; }
        [NotMapped]
        public int? TinhTrang_PheDuyet { get; set; }
    }
}

QuanLyYTe/Controllers/TrinhKyController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using QuanLyYTe.Models;
using QuanLyYTe.Repositorys;
using Microsoft.AspNetCore.Mvc.Rendering;
using ExcelDataReader;
using System.Data;
using System.Security.Claims;
using Microsoft.Kiota.Abstractions;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Hosting;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.VariantTypes;
using Microsoft.Office.Interop.Excel;
using DocumentFormat.OpenXml.Drawing.Charts;

namespace QuanLyYTe.Controllers
{
    public class TrinhKyController : Controller
    {
        private readonly DataContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public TrinhKyController(DataContext _context, IWebHostEnvironment webHostEnvironment)
        {
            this._context = _context;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index(string search, int page = 1)
        {   var MNV = User.FindFirstValue(ClaimTypes.Name);
            var check = _context.TaiKhoan.Where(x => x.TenDangNhap == MNV).FirstOrDefault();
            var res = await (from a in _context.TrinhKy
                             join nv in _context.NhanVien on a.NguoiLap equals nv.ID_NV
                             join bp in _context.PhongBan on a.ID_PhongBan equals bp.ID_PhongBan
                             select new TrinhKy
                             {
                                 ID_TK = a.ID_TK,
                                 ID_PhongBan = (int)a.ID_PhongBan,
                                 TenPhongBan = bp.TenPhongBan,
                                 NoiDung = a.NoiDung,
                                 NgayTrinhKy = (DateTime?)a.NgayTrinhKy ?? default,
                                 FilePath = a.FilePath,
                                 NguoiLap = (int?)a.NguoiLap??default,
                                 HoTen_NguoiLap = nv.HoTen,
                                 TinhTrang_NguoiLap = (int?)a.TinhTrang_NguoiLap?? default,
                                 Ngay_NguoiLap = (DateTime?)a.Ngay_NguoiLap?? default,
                                 TruongPho = (int?)a.TruongPho ?? default,
                                 TinhTrang_TruongPho = (int?)a.TinhTrang_TruongPho?? default,
                                 Ngay_TruongPho = (DateTime?)a.Ngay_TruongPho??default,
                                 GhiChu = a.GhiChu

                             }).ToListAsync();
            if (check.ID_Quyen != 1 && check.ID_Quyen != 2)
            {
                res = res.Where(x => x.ID_PhongBan == check.ID_PhongBan).ToList();
            }
            if (search != null)
            {
                res = res.Where(x => x.TenPhongBan.Contains(search) || x.NoiDung.Contains(search)).ToList();
            }
            const int pageSize = 20;
            if (page < 1)
            {
                page = 1;
            }
            int resCount = res.Count;
            var pager = new Pager(resCount, page, pageSize);
            int recSkip = (page - 1) * pageSize;

            var ordered = res.OrderByDescending(x => x.NgayTrinhKy);
            var data = ordered.Skip(recSkip).Take(pager.PageSize).ToList();

            this.ViewBag.Pager = pager;
            return View(data);

        }
        public FileResult TestDownloadPCF()
        {
            string filePath = "Form files/BM_KSK_BenhNgheNghiep.xlsx";
            HttpContext.Response.ContentType = "application/xlsx";
            FileContentResult result = new FileContentResult
            (System.IO.File.ReadAllBytes(filePath), "application/xlsx")
            {
                FileDownloadName = "BM_KSK_BenhNgheNghiep.xlsx"
            };
            return result;
        }
        public async Task<IActionResult> Create()
        {
            List<PhongBan> pb = _context.PhongBan.ToList();
            ViewBag.PBList = new SelectList(pb, "ID_PhongBan", "TenPhongBan");

            return PartialView();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file, TrinhKy _DO)
        {
            try
            {
                var Ma_NV = User.FindFirstValue(ClaimTypes.Name);
                var check_nv_kt = _context.NhanVien.Where(x=>x.MaNV == Ma_NV).FirstOrDefault();
                int ID_ky = 0;
                if (check_nv_kt != null)
                {
                    var idOutputParam = new SqlParameter
                    {
                        ParameterName = "@ID_OUT",
                        SqlDbType = SqlDbType.Int,
                        Direction = ParameterDirection.Output
                    };

                    SqlParameter[] sqlParameters = new SqlParameter[]
                    {
                        new SqlParameter("@ID_PhongBan", SqlDbType.Int) { Value = _DO.ID_PhongBan },
                        new SqlParameter("@NoiDung", SqlDbType.NVarChar) { Value = (object)_DO.NoiDung ?? DBNull.Value },
                        new SqlParameter("@NgayTrinhKy", SqlDbType.Date) { Value = _DO.NgayTrinhKy.HasValue ? _DO.NgayTrinhKy.Value : DBNull.Value },
                        new SqlParameter("@FilePath", SqlDbType.NVarChar) { Value = DBNull.Value },
                        new SqlParameter("@NguoiLap", SqlDbType.Int) { Value = check_nv_kt.ID_NV },
                        new SqlParameter("@TinhTrang_NguoiLap", SqlDbType.Int) { Value = 0 },
                        idOutputParam // OUTPUT Parameter
                    };

                    // Gọi stored procedure
                    _context.Database.ExecuteSqlRaw(
                        "EXEC TrinhKy_insert1 @ID_PhongBan, @NoiDung, @NgayTrinhKy, @FilePath, @NguoiLap, @TinhTrang_NguoiLap, @ID_OUT OUTPUT",
                        sqlParameters
                    );
                    ID_ky = (int)idOutputParam.Value;
                   
                }
                if (file == null || file.Length == 0)
                {
                    return RedirectToAction("Index", "ThoiHan_KSK_BNN");
                }


                // Create the Directory if it is not exist
                string webRootPath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), "wwwroot");
                string dirPath = Path.Combine(webRootPath, "ReceivedReports");
                if (!Directory.Exists(dirPath))
                {
                    Directory.CreateDirectory(dirPath);
                }

                // MAke sure that only Excel file is used 
                string dataFileName = Path.GetFileName(DateTime.Now.ToString("yyyyMMddHHmm"));

                string extension = Path.GetExtension(dataFileName);

                string[] allowedExtsnions = new string[] { ".xls", ".xlsx" };
                // Make a Copy of the Posted File from the Received HTTP Request
                string saveToPath = Path.Combine(dirPath, dataFileName);

                using (FileStream stream = new FileStream(saveToPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                // USe this to handle Encodeing differences in .NET Core
              /*  System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);
                read the excel file*/
                IExcelDataReader reader = null;
                using (var stream = new FileStream(saveToPath, FileMode.Open))
                {
                    if (extension == ".xlsx")
                        reader = ExcelReaderFactory.CreateBinaryReader(stream);
                    else
                        reader = ExcelReaderFactory.CreateOpenXmlReader(stream);

                    DataSet ds = new DataSet();
                    ds = reader.AsDataSet();
                    reader.Close();
                    if (ds != null && ds.Tables.Count > 0)
                    {
                        System.Data.DataTable serviceDetails = ds.Tables[0];

                        for (int i = 5; i < serviceDetails.Rows.Count; i++)
                        {
                            string MNV = serviceDetails.Rows[i][1].ToString().Trim();
                            var check_nv = _context.NhanVien.Where(x => x.MaNV == MNV).FirstOrDefault();
                            if (check_nv == null)
                            {
                                var Delete_BNN = _context.KSK_BenhNgheNghiep.Where(x => x.ID_TK == ID_ky).ToList();
                                foreach (var y in Delete_BNN)
                                {
                                    var Delete_ = _context.Database.ExecuteSqlRaw("EXEC KSK_BenhNgheNghiep_delete {0}", y.ID_KSK_BNN);
                                }
                                var Delete = _context.TrinhKy.Where(x => x.ID_TK == ID_ky).ToList();
                                var Delete_TK = _context.Database.ExecuteSqlRaw("EXEC TrinhKy_delete {0}", ID_ky);
                                TempData["msgSuccess"] = "<script>alert('Vui lòng cập nhật dữ liệu nhân viên: " + MNV + "');</script>";
                                return RedirectToAction("Index", "KSK_ChuyenViTri");
                            }

                            string ViTriLaoDong = serviceDetails.Rows[i][3].ToString().Trim();
                            var check_vt = _context.ViTriLaoDong.Where(x => x.TenViTriLaoDong.Trim() ==ViTriLaoDong.Trim()).FirstOrDefault();
                            if (check_vt == null)
                            {
                                var Delete_BNN = _context.KSK_BenhNgheNghiep.Where(x => x.ID_TK == ID_ky).ToList();
                                foreach (var y in Delete_BNN)
                                {
                                    var Delete_ = _context.Database.ExecuteSqlRaw("EXEC KSK_BenhNgheNghiep_delete {0}", y.ID_KSK_BNN);
                                }

QuanLyYTe/Views/TrinhKy/Approve.cshtml
@model QuanLyYTe.Models.TrinhKy
<script src="~/Chonse/chosen.jquery.js"></script>
<link href="~/Chonse/chosen.css" rel="stylesheet">
@using (Html.BeginForm("Approve", "TrinhKy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID_TK)
    @Html.HiddenFor(model => model.TinhTrang_PheDuyet)
    <div class="modal-dialog">
        <div class="modal-content" style="max-width: 2000px;">
            <div class="modal-header">
                <h5 id="ModalTitle"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
@*                @{
                    var selectListCavet = new SelectList(
                    new List<SelectListItem> {
                        new SelectListItem { Value = "1" , Text = "Phê duyệt" },
                        new SelectListItem { Value = "2" , Text = "Không phê duyệt" }
                                           }, "Value", "Text");
                }
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Tình trang phê duyệt</label>
                        @Html.DropDownListFor(model => model.TinhTrang_PheDuyet, selectListCavet as SelectList, "------  Chọn tình trạng phê duyệt  -------", new { @class = "form-control", @style="text-align: center;" })
                        @Html.ValidationMessageFor(model => model.TinhTrang_PheDuyet, "", new { @class = "text-danger" })
                    </div>
                </div>*@
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Ghi chú</label>
                        @Html.EditorFor(model => model.GhiChu, new { htmlAttributes = new { @class = "form-control", placeholder = "Ghi chú", @id = "NoiDung" } })
                        @Html.ValidationMessageFor(model => model.GhiChu, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" style="border-radius: 10px;margin-right: 4%;" value="Xác nhận" id="btnSubmit" class="btn btn-primary pull-right" />
            </div>
        </div>
    </div>
}
<style>
    .modal-body {
        box-sizing: border-box;
        display: flex;
        flex: 1;
        flex-direction: column;
        max-height: 750px;
        overflow: auto;
        -webkit-overflow-scrolling: touch;
        padding: 16px 16px;
    }
</style>
<script type="text/javascript">
    $("#ID_PhongBan").chosen({
        width: "100%"
    });
</script>

QuanLyYTe/Views/TrinhKy/CheckInformation.cshtml
@model QuanLyYTe.Models.TrinhKy
<script src="~/Chonse/chosen.jquery.js"></script>
<link href="~/Chonse/chosen.css" rel="stylesheet">
@using (Html.BeginForm("CheckInformation", "TrinhKy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID_TK)

    <div class="modal-dialog">
        <div class="modal-content" style="max-width: 2000px;">
            <div class="modal-header">
                <h5 id="ModalTitle"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="col-md-12 " style="text-align: center;">
                    <label class="form-label fw-bold">Trưởng phó BP/NM</label>
                    @Html.DropDownListFor(model => model.TruongPho, ViewBag.TPBPList as SelectList, "---- Chọn trưởng phó BP/NM ----", new { @style="text-align: center;", @id = "TruongPho", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TruongPho, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" style="border-radius: 10px;margin-right: 4%;" value="Xác nhận" id="btnSubmit" class="btn btn-primary pull-right" />
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $("#TruongPho").chosen({
        width: "100%"
    });
</script>

QuanLyYTe/Views/TrinhKy/Create.cshtml
@model QuanLyYTe.Models.TrinhKy

<script src="~/Chonse/chosen.jquery.js"></script>
<link href="~/Chonse/chosen.css" rel="stylesheet">


@using (Html.BeginForm("Create", "TrinhKy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog">
        <div class="modal-content" style="max-width: 2000px;">
            <div class="modal-header">
                <h5 id="ModalTitle"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Nội dung trích yếu</label>
                        @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control", placeholder = "Nội dung trích yếu", @id = "NoiDung" } })
                        @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Bộ phận nhà máy</label>
                        @Html.DropDownListFor(model => model.ID_PhongBan, ViewBag.PBList as SelectList, "---- Chọn bộ phận nhà máy ----", new { @style="text-align: center;", @id = "ID_PhongBan", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ID_PhongBan, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Ngày trình ký</label>
                        @Html.EditorFor(model => model.NgayTrinhKy, new { @value = DateTime.Today, htmlAttributes = new { @class = "form-control", @type = "date", placeholder = "Ngày trình ký", @id = "NgayTrinhKy" } })
                        @Html.ValidationMessageFor(model => model.NgayTrinhKy, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Chọn file Excel Import</label>
                        <input style="height: 41px;" type="file" id="file" name="file" class="form-control" onchange="checkfile(this);" />
                    </div>
                </div>
            </div>
            <div class="form-group">
                <a href="@Url.Action("TestDownloadPCF", "TrinhKy")" style="font-size:15px;padding-right: 35%;"> <i class="fa fa-download" aria-hidden="true"></i> Tải biểu mẫu Import </a>
                <input type="submit" style="border-radius: 10px;margin-right: 4%;" value="Xác nhận" id="btnSubmit" class="btn btn-primary pull-right" />
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $("#ID_PhongBan").chosen({
        width: "100%"
    });
</script>

QuanLyYTe/Views/TrinhKy/Edit.cshtml
@model QuanLyYTe.Models.TrinhKy
<script src="~/Chonse/chosen.jquery.js"></script>
<link href="~/Chonse/chosen.css" rel="stylesheet">
@using (Html.BeginForm("Edit", "TrinhKy", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID_TK)

    <div class="modal-dialog">
        <div class="modal-content" style="max-width: 2000px;">
            <div class="modal-header">
                <h5 id="ModalTitle"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Nội dung trích yếu</label>
                        @Html.EditorFor(model => model.NoiDung, new { htmlAttributes = new { @class = "form-control", placeholder = "Nội dung trích yếu", @id = "NoiDung" } })
                        @Html.ValidationMessageFor(model => model.NoiDung, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Bộ phận nhà máy</label>
                        @Html.DropDownListFor(model => model.ID_PhongBan, ViewBag.PBList as SelectList, "---- Chọn bộ phận nhà máy ----", new { @style="text-align: center;", @id = "ID_PhongBan", @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ID_PhongBan, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" style="text-align: center;">
                        <label class="form-label fw-bold">Ngày lên danh sách</label>
                        @Html.TextBox("NgayTrinhKy", null, new { @id = "NgayTrinhKy", @type = "date", @class = "form-control",@Value = ViewBag.NgayTrinhKy})
                        @Html.ValidationMessageFor(model => model.NgayTrinhKy, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" style="border-radius: 10px;margin-right: 4%;" value="Xác nhận" id="btnSubmit" class="btn btn-primary pull-right" />
            </div>
        </div>
    </div>
}
<style>
    .modal-body {
        box-sizing: border-box;
        display: flex;
        flex: 1;
        flex-direction: column;
        max-height: 750px;
        overflow: auto;
        -webkit-overflow-scrolling: touch;
        padding: 16px 16px;
    }
</style>
<script type="text/javascript">
    $("#ID_PhongBan").chosen({
        width: "100%"
    });
</script>

QuanLyYTe/Views/TrinhKy/Export.cshtml
<script src="~/Chonse/chosen.jquery.js"></script>
<link href="~/Chonse/chosen.css" rel="stylesheet">

    <div class="modal-dialog">
        <div class="modal-content" style="max-width: 2000px;">
            <div class="modal-header">
                <h5 id="ModalTitle"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12 " style="text-align: center;">
                        <label class="form-label fw-bold">Bộ phận nhà máy</label>
                        @Html.DropDownList("ID_PhongBan", ViewBag.PBList as SelectList, "---- Chọn bộ phận nhà máy ----", new { @style = "text-align: center;z-index:100", @id = "ID_PhongBan", @class = "form-control" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" style="text-align: center;">
                        <label class="form-label fw-bold">Ngày lên danh sách</label>
                        @Html.TextBox("NgayTrinhKy", null, new {  @id = "NgayTrinhKy", @type = "date", @class = "form-control", @Value = ViewBag.NgayTrinhKy })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="button" style="border-radius: 10px;margin-right: 4%;" value="Xác nhận" id="btnSubmit" class="btn btn-primary pull-right" />
            </div>
        </div>
    </div>
<style>
    .modal-body {
        box-sizing: border-box;
        display: flex;
        flex: 1;
        flex-direction: column;
        max-height: 750px;
        /* overflow: auto; */
        -webkit-overflow-scrolling: touch;
        padding: 16px 16px;
    }
</style>
<script type="text/javascript">
    $("#ID_PhongBan").chosen({
        width: "100%"
    });
    $("#btnSubmit").click(function(){
        var id=$("#ID_PhongBan").val();
        var ngay=$("#NgayTrinhKy").val();
        window.location.href = '@Url.Action("exportEX","TrinhKy")'+'?id='+id+'&ngay='+ ngay;
    });
</script>